# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, 'Niedostateczny'), (2, 'Dopuszczający'), (3, 'Dostateczny'), (4, 'Dobry'), (5, 'Bardzo Dobry'), (6, 'Celujący')])),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Imię')),
            ],
            options={
                'verbose_name': 'Przedmiot',
                'verbose_name_plural': 'Przedmioty',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nazwisko')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal', models.CharField(max_length=255)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_eschool_manager.student_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Uczeń',
                'verbose_name_plural': 'Ucznowie',
            },
        ),
        migrations.AddField(
            model_name='schoolgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eschool_manager.Student'),
        ),
        migrations.AddField(
            model_name='schoolgrade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eschool_manager.SchoolSubject'),
        ),
    ]
