# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eschool_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Miejscowość'),
        ),
        migrations.AlterField(
            model_name='student',
            name='postal',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kod pocztowy'),
        ),
    ]
